version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: "db_gedung_docker"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: "gedung_docker"
    ports:
      - 8100:80
    volumes:
      - ./:/var/www/html
