version: "3.5"

services:
  gedung-laravel:
    build:
      context: "."
      args:
        uid: ${UID}
    container_name: gedung-laravel
    ports:
      - 8100:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      backend:
        aliases:
          - app

  mysql-db-gedung:
    image: mysql:5.7
    container_name: mysql-db-gedung
    ports:
      - 3310:3306
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "db_gedung_docker"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    networks:
      backend:
        aliases:
          - mysql-db-gedung

networks:
  backend:
    name: backend-network-gedung
